MoneyEZ-FUHCM/moneyez-mobile

components/ProgressCircleComponent.tsx, components/index.ts, package.json, yarn.lock
implement common progress circle component
=> [COMMON][UI]imp. implement common progress circle component

components/ProgressCircleComponent.tsx
=> [MOD]fix. fix common

app/(tabs)/(group)/group-details/group-home/group-fund-remind/GroupFundRemind.translate.ts, app/(tabs)/(group)/group-details/group-home/group-fund-remind/GroupFundRemind.tsx, app/(tabs)/(group)/group-details/group-home/group-fund-remind/hooks/useGroupFundRemind.ts, app/(tabs)/(group)/group-details/group-home/group-home-default/GroupHomeDefault.tsx, app/(tabs)/(group)/group-details/group-home/group-home-default/hooks/useGroupHomeDefault.ts, components/ProgressCircleComponent.tsx, helpers/constants/pathname.ts
This pull request introduces a new feature for group fund reminders, including translations, UI components, hooks, and routing updates. The most important changes are summarized below:
* [`GroupFundRemind.translate.ts`](diffhunk://#diff-c718c675c027f436a236db8332a5bbafafe76ab688bd922c094a46dafcd4fa95R1-R50): Added a comprehensive set of translations for the group fund reminder feature.
* [`GroupFundRemind.tsx`](diffhunk://#diff-89b731796b3b7db555e616616ab664f346d683c47de7525f766fbfe73026a01cR1-R270): Implemented the UI for the group fund reminder page, including form validation, member list, and tab navigation.
* [`useGroupFundRemind.ts`](diffhunk://#diff-3b5488610e2c91b3f97fb711b02a5539be28ae41d4d727696c4ddcaf149822d1R1-R101): Created a custom hook to manage the state and handlers for …
=> [UI][FUND-REMIND] Implement UI of Group Fund Remind Page

app/(tabs)/(group)/group-details/group-home/group-home-default/GroupHomeDefault.tsx, app/(tabs)/(group)/group-details/group-home/group-home-default/hooks/useGroupHomeDefault.ts, app/(tabs)/(group)/group-details/group-home/withdraw-fund-request/WithdrawFundRequest.translate.ts, app/(tabs)/(group)/group-details/group-home/withdraw-fund-request/WithdrawFundRequest.tsx, app/(tabs)/(group)/group-details/group-home/withdraw-fund-request/hooks/useWithdrawFundRequest.ts, helpers/constants/pathname.ts
This pull request introduces a new feature for creating fund withdrawal requests in a group home setting. The changes include adding a new handler for the withdrawal request, updating the navigation paths, and creating new components and hooks to support the feature.
* [`app/(tabs)/(group)/group-details/group-home/group-home-default/GroupHomeDefault.tsx`](diffhunk://#diff-1735f03cf30806167e9cafb565f84f1df7f71641b1d6c60ca567a8207aef57cfR63): Added a new handler to initiate the fund withdrawal request.
* [`app/(tabs)/(group)/group-details/group-home/group-home-default/hooks/useGroupHomeDefault.ts`](diffhunk://#diff-605513d093749892432e03eda764bd26230c41e291fd05ee3cf0cbf6c5849970R4-R32): Introduced a new `handleCreateWithdrawRequest` function and updated the return object to include this …
=> [UI][FUND-WITHDRAW] Implement UI of Group Fund Withdraw Request Page

app/(auth)/forgot-password/ConfirmEmail.tsx, app/(auth)/forgot-password/InputOtp.tsx, app/(auth)/forgot-password/SetNewPassword.tsx, app/(tabs)/(bot)/BotScreen.const.ts, app/(tabs)/(bot)/chatbot/ChatMessage.tsx, app/(tabs)/(bot)/chatbot/ChatMessageItem.tsx, app/(tabs)/(bot)/hooks/useChatbotScreen.ts, app/(tabs)/(home)/expenses/expense-detail/ExpenseDetail.tsx, app/(tabs)/(home)/expenses/update-expense/hooks/useUpdateExpense.ts, components/BackScreenButton.tsx, components/ExpenseDetailCustom/BarChartExpenseCustom.tsx, components/ExpenseDetailCustom/hooks/useBarChart.ts, enums/globals.ts, helpers/formatCurrency.ts, helpers/libs/index.ts, redux/hooks/systemSelector.ts, redux/slices/systemSlice.ts, services/bot.ts, services/spendingModel.ts, types/bot.types.ts
=> [CHATBOT][API]imp. integrate API chatbot history

services/group.ts
fix path api create fund request
=> [GROUP_FUND][FIXBUG][API]fix. fix path api create fund request

app/(auth)/hooks/useLoginScreen.ts
=> [FIXBUG]fix. fix login google

app/(tabs)/(home)/expenses/update-expense/UpdateExpense.tsx, app/(tabs)/(home)/notification/hooks/useNotificationList.ts
=> [FIXBUG]fix. fixbug notice

app/(auth)/hooks/useLoginScreen.ts, app/(tabs)/(group)/Group.tsx, app/(tabs)/(group)/group-details/group-home/group-home-default/hooks/useGroupHomeDefault.ts, app/(tabs)/(group)/hooks/useGroupList.ts, app/(tabs)/(home)/notification/NotificationList.tsx, app/(tabs)/(home)/notification/hooks/useNotificationList.ts, app/(tabs)/_layout.tsx, enums/globals.ts
=> [FEATURE][GROUP]imp. implement deep linking

app/(tabs)/(home)/quiz/QuizScreen.tsx, app/(tabs)/(home)/quiz/components/QuizQuestion.tsx, app/(tabs)/(home)/quiz/components/SpendingModelReview.tsx, app/(tabs)/(home)/quiz/components/SuggestionPage.tsx, app/(tabs)/(home)/quiz/hooks/useQuiz.ts, redux/slices/apiSlice.ts, services/quiz.ts, types/quiz.types.ts
This pull request includes several changes to the `QuizScreen` and its components to enhance functionality and improve user experience. The most important changes include adding new states and handlers for quiz submission, updating button states, and integrating API data for spending models.
* [`app/(tabs)/(home)/quiz/QuizScreen.tsx`](diffhunk://#diff-dc0ebbfe13a3918f18066bb8556970fba51f7fee3b774e9fef5070448dbb91d0L1-R1): Added new states (`isSubmitting`, `quizSubmitResponse`, and `error`) and handlers to manage quiz submission and error states. Introduced `useEffect` for fetching active quizzes on component mount. Updated `BottomButtons` and `renderContent` to handle new states and conditions. [[1]](diffhunk://#diff-dc0ebbfe13a3918f18066bb8556970fba51f7fee3b774e9fef5070448dbb91d0L1-R1) …
=> [QUIZ][API]imp. implement API integrate of Quiz action

app/(tabs)/(group)/group-details/group-home/action-log-history/ActionLogHistory.constant.ts, app/(tabs)/(group)/group-details/group-home/action-log-history/ActionLogHistory.translate.ts, app/(tabs)/(group)/group-details/group-home/action-log-history/ActionLogHistory.tsx, app/(tabs)/(group)/group-details/group-home/action-log-history/hooks/useActionLogHistory.tsx, app/(tabs)/(group)/group-details/group-home/edit-log-history/EditLogHistory.translate.ts, app/(tabs)/(group)/group-details/group-home/edit-log-history/EditLogHistory.tsx, app/(tabs)/(group)/group-details/group-home/group-home-default/GroupHomeDefault.tsx, app/(tabs)/(group)/group-details/group-home/group-home-default/hooks/useGroupHomeDefault.ts, services/transaction.ts
=> [ACTION_LOG_HISTORY][UI][API]imp. implement action log history

app/(tabs)/(group)/group-details/group-home/edit-log-history/EditLogHistory.tsx
=> [MOD]mod. modify edit log history

app.json, app/(tabs)/(group)/Group.tsx, app/(tabs)/(group)/group-details/member/inivite-member/InviteMember.translate.ts, app/(tabs)/(group)/group-details/member/inivite-member/InviteMember.tsx, app/(tabs)/(group)/group-details/member/inivite-member/hooks/useInviteMember.ts, app/(tabs)/(group)/group-details/member/inivite-member/invite-member-by-QR-code/InviteMemberByQRCode.translate.ts, app/(tabs)/(group)/group-details/member/inivite-member/invite-member-by-QR-code/InviteMemberByQRCode.tsx, app/(tabs)/(group)/group-details/member/inivite-member/invite-member-by-QR-code/hooks/useInviteMemberByQRCode.ts, app/(tabs)/(group)/hooks/useGroupList.ts, helpers/constants/color.ts, package.json, services/group.ts, types/group.type.ts, yarn.lock
implement join group by scan QR code
=> [JOIN_GROUP_QR][API]imp. implement join group by scan QR code

app/(tabs)/(group)/group-details/group-home/create-fund-request/hooks/useCreateFundRequest.ts, app/(tabs)/(group)/group-details/group-home/fund-request-info/FundRequestInfo.translate.ts, app/(tabs)/(group)/group-details/group-home/fund-request-info/FundRequestInfo.tsx, app/(tabs)/(group)/group-details/group-home/fund-request-info/hooks/useFundRequestInfo.ts, app/(tabs)/(group)/group-details/group-home/withdraw-fund-request/hooks/useWithdrawFundRequest.ts, app/(tabs)/(group)/group-details/member/inivite-member/InviteMember.tsx, app/(tabs)/(group)/group-details/member/inivite-member/hooks/useInviteMember.ts
=> [GROUP_FUND][MOD]mod. change content 

app/(tabs)/(home)/notification/hooks/useNotificationList.ts, app/(tabs)/_layout.tsx, redux/slices/notificationSlice.ts, redux/store.ts
=> [NOTIFICATION][FIXBUG]fix. fix notice list

app/(tabs)/(account)/bank-account/function-bank-account/hooks/useFunctionBankAccount.ts, app/(tabs)/(group)/create-group/function-bank-account/FunctionBankAccount.constant.ts, app/(tabs)/(group)/create-group/function-bank-account/FunctionBankAccount.translate.ts, app/(tabs)/(group)/create-group/function-bank-account/hooks/useFunctionBankAccount.ts, app/(tabs)/(home)/expenses/expense-detail/ExpenseDetail.tsx, app/(tabs)/(home)/expenses/expense-detail/hooks/useExpenseDetail.ts, app/(tabs)/(home)/spending-budget-list/SpendingBudgetList.tsx, app/(tabs)/(home)/spending-budget-list/hooks/useSpendingBudgetList.ts, components/ExpenseDetailCustom/BarChartExpenseCustom.tsx
=> [FIXBUG]fix. fixbug

app/(tabs)/(group)/group-details/group-home/group-fund-remind/GroupFundRemind.tsx, app/(tabs)/(group)/group-details/group-home/group-statistic/GroupStatistic.tsx, app/(tabs)/(group)/group-details/group-setting/group-setting-default/GroupSettingDefault.tsx, app/(tabs)/(home)/add-transaction/AddTransaction.tsx, app/(tabs)/(home)/expenses/expense-detail/ExpenseDetail.tsx, app/(tabs)/(home)/expenses/expense-detail/hooks/useExpenseDetail.ts, app/(tabs)/(home)/expenses/update-expense/hooks/useUpdateExpense.ts, app/(tabs)/(home)/notification/hooks/useNotificationList.ts, app/(tabs)/(home)/period-history/PeriodHistoryDetail.tsx, app/(tabs)/(home)/recurring-transaction/recurring-transaction-list/RecurringTransactionList.tsx, app/(tabs)/(home)/spending-budget-list/SpendingBudgetList.translate.ts, app/(tabs)/(home)/spending-budget-list/SpendingBudgetList.tsx, app/(tabs)/(home)/spending-budget-list/hooks/useSpendingBudgetList.ts, app/(tabs)/(home)/spending-model-history/SpendingModelHistory.tsx, app/(tabs)/(home)/statistic-overview/StatisticOverview.tsx, app/(tabs)/(home)/statistic-overview/balance-report/BalanceReport.tsx, app/(tabs)/(home)/statistic-overview/recurring-transactions-calendar/CalendarView.tsx, app/(tabs)/(home)/statistical/CalendarView.tsx, app/(tabs)/(home)/transaction-detail/TransactionDetail.tsx, components/BarChartCustom/BarChartCustom.tsx, components/ExpenseDetailCustom/BarChartExpenseCustom.tsx, components/FlatListCustom.tsx, components/FlatListGestureCustom.tsx, components/ProgressCircleComponent.tsx, components/TabBarCustom/TabBarButton.tsx
=> [FIXBUG]fix. fixbug app

app/(tabs)/(home)/home-screen/HomeScreen.tsx, app/(tabs)/(home)/home-screen/hooks/useHomeScreen.ts, app/(tabs)/(home)/post/PostDetail.tsx, app/(tabs)/(home)/post/PostList.tsx, app/(tabs)/(home)/post/hooks/usePost.ts, app/(tabs)/(home)/post/hooks/usePostDetail.ts, app/(tabs)/(home)/post/post.translate.ts, components/TabBarCustom/TabBar.tsx, helpers/constants/pathname.ts, services/post.ts, types/post.types.ts
=> [POST]imp. implement post

app/(tabs)/(group)/group-details/group-home/group-statistic/GroupStatistic.tsx, app/(tabs)/(group)/group-details/group-setting/group-financial-goal/GroupFinancialGoal.tsx
=> [MOD]mod. fix style

app/(tabs)/(account)/bank-account/bank-account-list/BankAccount.tsx, app/(tabs)/(group)/create-group/bank-account-list/BankAccount.tsx, app/(tabs)/(group)/group-details/group-setting/group-financial-goal/GroupFinancialGoal.translate.ts, app/(tabs)/(group)/group-details/group-setting/group-financial-goal/hooks/useGroupFinancialGoal.ts, app/(tabs)/(home)/HomeScreen.const.ts, app/(tabs)/(home)/recurring-transaction/recurring-transaction-form/RecurringTransactionForm.tsx, app/(tabs)/(home)/recurring-transaction/recurring-transaction-list/RecurringTransactionList.translate.ts, app/(tabs)/(home)/recurring-transaction/recurring-transaction-list/RecurringTransactionList.tsx, app/(tabs)/(home)/statistic-overview/balance-report/BalanceReport.tsx, app/(tabs)/(home)/statistic-overview/balance-report/hooks/useBalanceReport.ts, app/(tabs)/(home)/statistic-overview/category-all-time/CategoryAllTime.tsx, app/(tabs)/(home)/statistic-overview/year-report/YearReport.tsx, app/(tabs)/(home)/statistic-overview/year-report/hooks/useYearReport.ts, helpers/types/recurringTransaction.types.ts
=> [REFACTOR]fix. fixbug + refactor

app/(tabs)/(account)/setting/AccountSetting.tsx, app/(tabs)/(account)/update-info/UpdateUserInfo.tsx, app/(tabs)/(group)/group-details/group-setting/group-setting-default/GroupSettingDefault.constant.ts, app/(tabs)/(group)/group-details/group-setting/group-setting-default/GroupSettingDefault.translate.ts, app/(tabs)/(group)/group-details/group-setting/group-setting-default/GroupSettingDefault.tsx, app/(tabs)/(group)/group-details/group-setting/group-setting-default/hooks/useGroupSettingDefault.ts, app/(tabs)/(group)/hooks/useCreateGroupScreen.ts, app/(tabs)/(home)/home-screen/HomeScreen.tsx
implement close group fund from leader
=> [GROUP]imp. implement close group fund from leader

app/(tabs)/(group)/create-group/bank-account-list/BankAccount.tsx, app/(tabs)/(home)/period-history/PeriodHistory.tsx, app/(tabs)/(home)/period-history/hooks/usePeriodHistory.ts, app/(tabs)/(home)/spending-budget-list/SpendingBudgetList.tsx, app/(tabs)/(home)/spending-budget-list/hooks/useSpendingBudgetList.ts, app/(tabs)/(home)/statistic-overview/recurring-transactions-calendar/CalendarView.tsx, components/SpendingBudgetComponent.tsx
fix UI + fixbug logic calendar
=> [MOD]mod. fix UI + fixbug logic calendar

app/(tabs)/(account)/bank-account/bank-account-list/BankAccount.tsx
=> [MOD]mod. mod style

app/(tabs)/(group)/group-details/member/inivite-member/InviteMember.tsx
=> [MOD]mod. change style UI
